### PR TITLE
Dynamic routing for plant details

### PR DESCRIPTION
**Pull request by anna-wro**
It's just an ugly skeleton, but it works
links like `localhost:3000/zawilec`

Screenshot 2020-12-19 at 19 29 25

Screenshot 2020-12-19 at 19 11 28

Screenshot 2020-12-19 at 14 55 15

#### I replaced "`isSafe` with `danger` score and assigned 4 to toxic plants that are not scored yet (then it will be 1-3)

### CODE REVIEW

**Comment by coderitual** [comment]
@anna-wro I will take a look. One thought is that the best would be to have routing working while keeping modal vibe for opening details view :)

**Comment by anna-wro** [comment]
@coderitual Ill try to do this before Wed, that would solve other issues I've had

**Comment by coderitual** [comment]
@anna-wro to achieve this in next the easiest way seems to handle master and details view in one "page" file and delegate particular work from there.

ref: https://nextjs.org/docs/routing/dynamic-routes#optional-catch-all-routes

**Comment by anna-wro** [comment]
@coderitual it works! 🎉

**Review by coderitual — APPROVED** [review]

**Pull request merged**
